{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.application_name }}-ingress
  labels:
    {{- toYaml .Values.labels | nindent 4 }}

spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:  
          - path: /
            pathType: Prefix
            
            backend:
              service:
                name: {{ .Values.application_name }}-svc
                port:
                  number: {{ .Values.service.port }}
{{- end }}